### ISSUE TITLE
Install via composer

### ISSUE THREAD

**Issue by duellsy** [m1x0n/helpscout-docs-api-php#1]
I understand this is probably no longer maintained, but is this installable via composer?

**Comment by m1x0n** [comment]
Hi @duellsy . I think you can install it via composer by simply add these lines to your composer.json:

```
"require": {
        "m1x0n/helpscout-docs-api-php": "@dev"
    },
    "repositories": [
        {
            "type": "vcs",
            "url":  "https://github.com/m1x0n/helpscout-docs-api-php.git"
        }
    ]
```

I'll try to register it on packagist after some refinements. 
All contributions are appreciated.

**Comment by duellsy** [comment]
Legend, thanks mate

**Comment by m1x0n** [comment]
Also it's possible to install it in common way:

```
composer require m1x0n/helpscout-docs-api-php
```

**Comment by duellsy** [comment]
Weird, I tried the common way previously, but didn't work. Adding the repo block worked a treat though :)
