### ISSUE TITLE
Feature request: pageSize parameter

### ISSUE THREAD

**Issue by adammeyer** [m1x0n/helpscout-docs-api-php#10]
Add support for the pageSize parameter when listing articles.

**Comment by m1x0n** [comment]
Hi @adammeyer. Feel free to create a PR with the feature you're looking for.

**Comment by m1x0n** [comment]
@adammeyer I managed to add feature you've requested. Could you please use version 1.3.0 and confirm that feature works as expected so we can close this issue?

**Comment by adammeyer** [comment]
@m1x0n Works great, thank you so much!
