### ISSUE TITLE
setName being skipped

### ISSUE THREAD

**Issue by kwcjr** [m1x0n/helpscout-docs-api-php#15]
when uploading an article, the docs API defaults to using the file name for the Title. (setName)

**Comment by m1x0n** [comment]
Hi @kwcjr . Thanks for pointing this out. In case you know how to solve this issue feel free to drop a PR.

**Comment by m1x0n** [comment]
I did rough investigation and came up with a PR. @kwcjr Could you please check if this change solves your issue?

**Comment by kwcjr** [comment]
Thanks for such fast debugging! I'll be checking this out tonight to see if it fixes the issue. Thanks again!

**Comment by kwcjr** [comment]
Hey @m1x0n - all seams good now on the "fix/upload-article-name" branch! Thank you very much for looking into this.

**Comment by m1x0n** [comment]
@kwcjr Released https://github.com/m1x0n/helpscout-docs-api-php/releases/tag/2.0.1
