### ISSUE TITLE
Add php8 support

### ISSUE THREAD

**Issue by m1x0n** [m1x0n/helpscout-docs-api-php#17]
In terms of php8 migration following changes should be made:

- [x] Moving to github actions
- [x] Adjust libraries dependencies: php8, guzzle
- [x] Try to automate refactoring with https://github.com/rectorphp/rector

**Comment by jljr222** [comment]
I just wanted to ask if this is now PHP 8 compatible. Thank you for your work!

**Comment by m1x0n** [comment]
Hi @jljr222 ! Frankly speaking I haven't tested all the functionality yet. Most of the work was done via rector in order to get use of some new features(mostly types related). On the other hand some basic tests already passed against php8 version.
Anyways if you find some glitches feel free to submit an issue.
Thanks for your interest!
