### ISSUE TITLE
Fatal Error on getArticlesForCollection()

### ISSUE THREAD

**Issue by jljr222** [m1x0n/helpscout-docs-api-php#22]
I updated my project to use 3.0.0 and I've noticed an error popping up when I'm attempting to pull the articles belonging to one of my collections. Here is the code:

```
$docsApiClient = new DocsApiClient('--snipped--');

// Get articles via collection
$popular_articles = $docsApiClient->getArticlesForCollection('--snipped--', 1, 'published', 'popular', 'desc', 5);
```

It generates the following error:

> PHP Fatal error:  Uncaught TypeError: Typed property HelpScoutDocs\\\\Models\\\\ArticleRef::$createdBy must be int or null, string used in /nas/content/live/swiftmodders/wp-content/themes/swiftmodders-wp/vendor/m1x0n/helpscout-docs-api-php/src/HelpScoutDocs/Models/ArticleRef.php:43\\nStack trace:\\n#0 /nas/content/live/swiftmodders/wp-content/themes/swiftmodders-wp/vendor/m1x0n/helpscout-docs-api-php/src/HelpScoutDocs/ResourceCollection.php(38): HelpScoutDocs\\\\Models\\\\ArticleRef->__construct(Object(stdClass))\\n#1 /nas/content/live/swiftmodders/wp-content/themes/swiftmodders-wp/vendor/m1x0n/helpscout-docs-api-php/src/HelpScoutDocs/Api/AbstractApi.php(319): HelpScoutDocs\\\\ResourceCollection->__construct(Object(stdClass), 'HelpScoutDocs\\\\\\\\M...')\\n#2 /nas/content/live/swiftmodders/wp-content/themes/swiftmodders-wp/vendor/m1x0n/helpscout-docs-api-php/src/HelpScoutDocs/Api/Article.php(82): HelpScoutDocs\\\\Api\\\\AbstractApi->getResourceCollection('collections/607...', Array, 'HelpScoutDocs\\\\\\\\M...')\\n#3 /nas/content/live/swiftmodders/wp-content/themes/swif in /nas/content/live/swiftmodders/wp-content/themes/swiftmodders-wp/vendor/m1x0n/helpscout-docs-api-php/src/HelpScoutDocs/Models/ArticleRef.php on line 43

**Comment by m1x0n** [comment]
It seems some tests should be added to test deserialization integrity. I'll check shortly.

**Comment by m1x0n** [comment]
@jljr222 The issue seems to be fixed in https://github.com/m1x0n/helpscout-docs-api-php/releases/tag/3.0.1
