### ISSUE TITLE
Article keywords

### ISSUE THREAD

**Issue by adammeyer** [m1x0n/helpscout-docs-api-php#34]
Is there a reason updating article keywords isn't supported?  https://developer.helpscout.com/docs-api/articles/update/

Would a PR adding this support be welcome?

**Comment by adammeyer** [comment]
https://github.com/m1x0n/helpscout-docs-api-php/pull/35

**Comment by m1x0n** [comment]
Hey @adammeyer . It could be whatever reason when something is missing or implemented wrongly. This project is open for collaboration.
I'll release your patch soon.
Thanks,  your contributions are always welcomed and appreciated.

**Comment by m1x0n** [comment]
Here is a new release: https://github.com/m1x0n/helpscout-docs-api-php/releases/tag/4.1.0
